name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghidra:
          - "11.2"
          - "11.1.2"
          - "11.1.1"

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.5
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: List files
      run: ls -lhR

    - name: Build
      run: gradle --console plain buildExtension
      working-directory: ./ghidra_yara
      env:
        GITHUB_TOKEN: ${{ secrets.READONLY_PUBLIC_REPO_PAT }}
        GITHUB_USERNAME: ${{ secrets.READONLY_PUBLIC_REPO_USER }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GhidraYara_Ghidra_${{ matrix.ghidra }}
        path: ghidra_yara/dist/*.zip

  release:
    runs-on: "ubuntu-latest"
    needs: build

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Download binaries
      uses: actions/download-artifact@v4

    - name: List files
      run: ls -lhR

    - name: Release nightly
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        generate_release_notes: true
        fail_on_unmatched_files: true
        prerelease: true
        tag_name: latest
        name: "GhidraYara Nightly (${{steps.date.outputs.date}})"
        files: GhidraYara_Ghidra_*/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release stable
      if: contains(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: stable
        name: "GhidraYara stable (${{ github.ref }}) (${{steps.date.outputs.date}})"
        draft: true
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: GhidraYara_Ghidra_*/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
